# Generated by Django 5.0.4 on 2024-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistake',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
