# Generated by Django 5.0.4 on 2024-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_mistakefactor_factor_mistakefactor_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='description',
        ),
        migrations.AddField(
            model_name='factor',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mistake',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
