# Generated by Django 5.0.6 on 2024-05-25 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('user', 'habit', 'date'), name='unique_habit_log'),
        ),
    ]
