# Generated by Django 5.0.6 on 2024-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog_unique_habit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='repeat_after',
            field=models.IntegerField(default=1),
        ),
    ]
