# Generated by Django 5.0.6 on 2024-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_repeat_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.TextField(default='Not set yet'),
        ),
    ]
