# Generated by Django 5.0.6 on 2024-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_is_active_alter_habit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
